server:
  port: 8082
  servlet:
    context-path: /country

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: country

  h2:
    console:
      enabled: true