version: '3.8'
services:
  discovery:
    image: pierreedimo777/houlala-cloud-discovery
    ports:
      - "8761:8761"
    restart: on-failure
  authentication-client:
    image: pierreedimo777/houlala-cloud-authentication-client
    expose:
      - 8088
    ports:
      - "8088:8088"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    restart: on-failure
  stock-service:
    image: pierreedimo777/houlala-cloud-stock-service
    container_name: stock-service
    expose:
      - "8089"
    ports:
      - "8089:8089"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://database:3306/stock?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "28Janvier1995?",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    restart: on-failure
  category-service:
    image: pierreedimo777/houlala-cloud-category-service
    container_name: category-service
    expose:
      - "8084"
    ports:
      - "8084:8084"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://database:3306/category?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "28Janvier1995?",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    restart: on-failure
  country-service:
    image: pierreedimo777/houlala-cloud-country-service
    container_name: country-service
    expose:
      - "8082"
    ports:
      - "8082:8082"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://database:3306/country?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "28Janvier1995?",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    restart: on-failure
  discovery-orchestrator:
    image: pierreedimo777/houlala-cloud-discovery-orchestrator
    container_name: discovery-orchestrator
    expose:
      - "8081"
    ports:
      - "8081:8081"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    restart: on-failure
  gateway:
    image: pierreedimo777/houlala-cloud-gateway
    ports:
      - "8080"
    depends_on:
      - discovery
      - discovery-orchestrator
      - authentication-client
      - inventory-service
      - houlala-marketplace-client
    environment:
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
      SPRING_PROFILES_ACTIVE: path
    restart: on-failure
  location-service:
    image: pierreedimo777/houlala-cloud-location-service
    container_name: location-service
    expose:
      - "8083"
    ports:
      - "8083:8083"
    environment:
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://database:3306/location?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "28Janvier1995?",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    restart: on-failure
  inventory-service:
    image: pierreedimo777/houlala-cloud-inventory-service
    container_name: inventory-service
    expose:
      - "8090"
    ports:
      - "8090:8090"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://database:3306/inventory?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "28Janvier1995?",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    restart: on-failure
  review-service:
    image: pierreedimo777/houlala-cloud-review-service
    container_name: review-service
    expose:
      - "8086"
    ports:
      - "8086:8086"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://database:3306/review?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "28Janvier1995?",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    restart: on-failure
  room-service:
    image: pierreedimo777/houlala-cloud-room-service
    container_name: room-service
    expose:
      - "8085"
    ports:
      - "8085:8085"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://database:3306/room?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "28Janvier1995?",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    restart: on-failure
  houlala_authentication:
    image: pierreedimo777/houlala-authentication
    expose:
      - "8010"
    ports:
      - "8010:8010"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8010
  houlala_storage:
    image: pierreedimo777/houlala-cloud-storage
    expose:
      - "8001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8001
    ports:
      - "8001:8001"
  houlala-marketplace-client:
    image: pierreedimo777/houlala-cloud-houlala-marketplace:latest
    container_name: houlala-marketplace-client
    expose:
      - "9090"
    depends_on:
      - "discovery"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    restart: on-failure
  marketplace-api:
    image: pierreedimo777/marketplace-api
    depends_on:
      - database
    ports:
      - "3000:3000"
    networks:
      - default
  MS_SQL:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ms-server-volume:/var/opt/mssql
    expose:
      - "1433"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "1Secure*Password1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - "8003:3000"
    volumes:
      - ms-server-volume:/root/.dbgate
    environment:
      CONNECTIONS: con1

      LABEL_con1: MsSql
      SERVER_con1: MS_SQL
      USER_con1: SA
      PASSWORD_con1: 1Secure*Password1
      PORT_con1: 1433
      ENGINE_con1: mssql@dbgate-plugin-mssql
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'pierre'
      MYSQL_PASSWORD: '28Janvier1995?'
      MYSQL_ROOT_PASSWORD: '28Janvier1995?'
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8092:80"
    environment:
      - PMA_ARBITRARY=1
volumes:
  my-db:
  ms-server-volume:

