server:
  port: 8089
  servlet:
    context-path: /stock

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: stock
  h2:
    console:
      enabled: true
