server:
  port: 8080

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  application.name: gateway-api
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5285/"
            allowedMethods:
              - GET
      discovery.locator.enabled: true
      routes:
        - id: discovery-orchestrator
          uri: lb://discovery-orchestrator
          predicates:
            Path=/discovery-orchestrator/**
        - id: authentication
          uri: lb://authentication
          predicates:
            Path=/authentication/**
        - id: marketplace
          uri: lb://marketplace
          predicates:
            Path=/marketplace/**
        - id: inventory
          uri: lb://inventory
          predicates:
            Path=/inventory/**
        - id: notification
          uri: lb://notification
          predicates:
            Path=/notification/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka