server:
  port: 4000

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  application.name: gateway-api
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5285/"
            allowedMethods:
              - GET
      discovery.locator.enabled: true
      routes:
        - id: discovery-orchestrator
          uri: lb://discovery-orchestrator
          predicates:
            Path=/discovery-orchestrator/**
        #          filters:
        #            - Jwt
        - id: authentication
          uri: lb://authentication
          predicates:
            Path=/authentication/**
        - id: marketplace
          uri: lb://marketplace
          predicates:
            Path=/marketplace/**
        #          filters:
        #            - Jwt
        - id: inventory
          uri: lb://inventory
          predicates:
            Path=/inventory/**
        #          filters:
        #            - Jwt
        - id: email
          uri: lb://email
          predicates:
            Path=/email/**
#          filters:
#            - Jwt
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka