server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: discovery-orchestrator
          uri: lb://discovery-orchestrator
          predicates:
            - Path=/**
