server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: orchestrator
          uri: lb://orchestrator
          predicates:
            - Path=/**
