server:
  port: 8081
  servlet:
    context-path: /discovery-orchestrator

spring:
  application:
    name: discovery-orchestrator

feign:
  client:
    config:
      default:
        errorDecoder: com.example.discoveryorchestrator.errordecoder.CountryErrorDecoder