server:
  port: 8087
  servlet:
    context-path: /marketplace

spring:
  application:
    name: marketplace

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

feign:
  client:
    config:
      default:
        error-decoder: com.example.marketplaceclient.errorDecoder.MarketplaceErrorDecoder

