server:
  port: 8087
  servlet:
    context-path: /marketplace

spring:
  application:
    name: marketplace

feign:
  client:
    config:
      default:
        error-decoder: com.example.marketplaceclient.errorDecoder.MarketplaceErrorDecoder

