server:
  port: 8081
  servlet:
    context-path: /orchestrator

spring:
  application:
    name: orchestrator

feign:
  client:
    config:
      default:
        errorDecoder: com.example.orchestrator.errordecoder.CountryErrorDecoder