server:
  port: 8088
  servlet:
    context-path: /authentication

spring:
  application:
    name: authentication

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        error-decoder: com.example.authenticationclient.decoder.AuthErrorDecoder

